import type { Metadata } from "next";
import { Montserrat, Alexandria } from 'next/font/google'; // Font wapis aa gaya
import "./globals.css";
import { ThemeProvider } from '@/context/ThemeContext';
import { connectDB } from "@/lib/db";
import SystemConfig from "@/models/SystemConfig";
import { SuspendedScreen } from "@/components/ui/SuspendedScreen";
import { headers } from "next/headers";

// Font configure kiya
const montserrat = Montserrat({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-montserrat' });
const alexandria = Alexandria({ subsets: ['latin'], weight: ['300', '400', '500', '700'], variable: '--font-alexandria' });

export const metadata: Metadata = {
  title: "Skill Grace School System",
  description: "Generated by Sharry",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // 🔴 SOFTWARE SUSPENSION CHECK 🔴
  await connectDB();
  const config = await SystemConfig.findOne({ key: 'software_status' });
  const isSuspended = config?.isSoftwareActive === false;

  const headerList = await headers();
  const pathname = headerList.get('x-pathname') || "";
  const isSecretRoute = pathname === '/sharyy326feesubmit';

  return (
    <html lang="en">
      {/* Body pe class lagayi */}
      <body className={`${montserrat.className} ${alexandria.variable}`}>
        <ThemeProvider>
          {(isSuspended && !isSecretRoute) ? <SuspendedScreen /> : children}
        </ThemeProvider>
      </body>
    </html>
  );
}